name: Prepare and transfer repository from gitlab
inputs:
  system:
    required: true
  app:
    required: true
  repo:
    required: true
  branch:
    required: true

runs:
  using: "composite"
  steps:
    - name: Scrape build settings
      id: scrape_settings
      shell: bash
      run: |
        source scripts/${{inputs.system}}/build-config.sh
        echo build_stage_dir=$BUILD_STAGE_DIR >> $GITHUB_OUTPUT
    - name: Initialising repository
      shell: bash
      run: |
        git init ${{ inputs.app }}
        pushd ${{ inputs.app }}
        git remote add origin https://gitlab.com/${{ inputs.repo }}.git
        git -c protocol.version=2 fetch --prune --no-recurse-submodules --depth=1 origin +refs/tags/${{ inputs.branch }}:refs/tags/${{ inputs.branch }}
        git checkout ${{ inputs.branch }}
        popd
    - name: Package ${{ inputs.app }}
      shell: bash
      run: |
        tar -cf ${{ inputs.app }}.tar ${{ inputs.app }}
    - name: Sync ${{ inputs.app }} to ${{ inputs.system }}
      shell: bash
      run: |
        scp ${{ inputs.app }}.tar ${{inputs.system}}:${{steps.scrape_settings.outputs.build_stage_dir}}/
