name: Setup ssh
inputs:
  system:
    required: true
  sshkey:
    required: true
  hostkey:
    required: true
  user:
    required: true

runs:
  using: "composite"
  steps:
    - name: Get system FQDN
      id: get_fqdn
      shell: bash
      run: | 
        fqdn=$( grep ${{inputs.system}}: .github/systems.txt )
        echo "fqdn=${fqdn//${{inputs.system}}:/}" >> $GITHUB_OUTPUT
    - name: Configure SSH
      shell: bash
      run: |
        echo ${{ steps.get_fqdn.outputs.systems }} 
        mkdir -p ~/.ssh/
        echo "${{inputs.sshkey}}" > ~/.ssh/${{inputs.system}}.key
        chmod 600 ~/.ssh/${{inputs.system}}.key
        echo "${{inputs.hostkey}}" >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts
        cat > ~/.ssh/config <<EOF
        Host ${{inputs.system}}
          Hostname ${{ steps.get_fqdn.outputs.fqdn }}
          User ${{inputs.user}}
          IdentityFile ~/.ssh/${{inputs.system}}.key
        EOF