name: Setup ssh
inputs:
  system:
    required: true
  sshkey:
    required: true
  hostkey:
    required: true
  user:
    required: true

runs:
  using: "composite"
  steps:
    - name: Get system FQDN
      id: get_fqdn
      shell: bash
      run: | 
        echo "systems=$( cat .github/systems.json )" >> $GITHUB_OUTPUT
    - name: Configure SSH
      shell: bash
      run: |
        echo ${{ steps.get_fqdn.outputs.systems }} 
        mkdir -p ~/.ssh/
        echo "${{inputs.sshkey}}" > ~/.ssh/${{inputs.system}}.key
        chmod 600 ~/.ssh/${{inputs.system}}.key
        echo "${{inputs.hostkey}}" >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts
        cat > ~/.ssh/config <<EOF
        Host ${{inputs.system}}
          Hostname ${{ fromJson( steps.get_fqdn.outputs.systems ) }}.${{ inputs.system }}
          User ${{inputs.user}}
          IdentityFile ~/.ssh/${{inputs.system}}.key
        EOF