name: Prepare and transfer repository
inputs:
  system:
    required: true
  app:
    required: true
  repo:
    required: true
  branch:
    required: true
  depth:
    required: false
  fetch_latest_tag:
    required: false

runs:
  using: "composite"
  steps:
    - name: Scrape build settings
      id: scrape_settings
      shell: bash
      run: |
        source scripts/${{inputs.system}}/build-config.sh
        echo build_stage_dir=$BUILD_STAGE_DIR >> $GITHUB_OUTPUT
    - name: Checkout ${{ inputs.app }}
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repo }}
        ref: ${{ inputs.branch }}
        path: ${{ inputs.app }}
        fetch-tags: true
        fetch-depth: ${{ inputs.depth || 1 }}
        lfs: true
    - name: Checkout latest tag
      if: ${{ inputs.fetch_latest_tag == 'true' }}
      shell: bash
      run: |
        pushd ${{ inputs.app }}
        git checkout $( git describe --tags --abbrev=0 )
        git status
        popd
    - name: Delete post-checkout git lfs hook
      shell: bash
      run: rm -f ${{ inputs.app }}/.git/hooks/post-checkout
    - name: Package ${{ inputs.app }}
      shell: bash
      run: |
        tar -cf ${{ inputs.app }}.tar ${{ inputs.app }}
    - name: Sync ${{ inputs.app }} to ${{ inputs.system }}
      shell: bash
      run: |
        scp ${{ inputs.app }}.tar ${{inputs.system}}:${{steps.scrape_settings.outputs.build_stage_dir}}/
