name: Prepare and transfer repository
description: Prepare this repository and transfer to an HPC system
inputs:
  system:
    required: true

runs:
  using: "composite"
  steps:
    - name: Sync repository to ${{inputs.system}}
      shell: bash
      run: |
        rsync -avz --delete --exclude=/.git/ --exclude=/.github/ ./ ${{inputs.system}}:"$REPO_PATH"
