name: Prepare and transfer repository
inputs:
  system:
    required: true
  repopath:
    required: true

runs:
  using: "composite"
  steps:
    - name: Sync repository to ${{inputs.system}}
      shell: bash
      run: |
        rsync -avz --delete --exclude=/.git/ --exclude=/.github/ ./ ${{inputs.system}}:${{inputs.repopath}}
