name: Build PETSc & Firedrake

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{secrets.GADI_TESTING_KEY}}" > ~/.ssh/gadi.key
        chmod 600 ~/.ssh/gadi.key
        echo "${{secrets.GADI_HOST_KEY}}" >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts
        cat > ~/.ssh/config <<EOF
        Host gadi
          Hostname gadi.nci.org.au
          User ${{secrets.GADI_USER}}
          IdentityFile ~/.ssh/gadi.key
        EOF
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Sync repository to Gadi
      run: |
        rsync -avz --delete --exclude=/.git/ --exclude=/.github/ ./ gadi:${{secrets.GADI_REPO_PATH}}
    - name: Checkout PETSc
      uses: actions/checkout@v4
      with:
        repository: firedrakeproject/petsc
        ref: firedrake
        path: petsc
    - name: Package Petsc
      run: |
        tar -cf petsc.tar petsc
    - name: Sync petsc to Gadi
      run: |
        scp petsc.tar gadi:${{secrets.GADI_REPO_PATH}}
    - name: Move petsc.tar to where its expected
      run: |
        ssh gadi "source ${{secrets.GADI_REPO_PATH}}/scripts/gadi/build-config.sh; mv ${{secrets.GADI_REPO_PATH}}/petsc.tar \${BUILD_STAGE_DIR}"