name: Custom Firedrake Build

on:
  workflow_dispatch:
    inputs:
      system:
        description: "Select a system to build on"
        required: true
        type: choice
        options:
          - gadi
          - setonix
      do_64bit:
        description: "Build petsc/firedrake with 64-bit indices?"
        required: false
        type: boolean
      build_branch:
        description: "Select a firedrake branch to build"
        required: true
        type: string
      firedrake_repo:
        description: "Select a firedrake repository to build (leave blank for firedrakeproject/firedrake)"
        required: false
        type: string

concurrency:
  group: ${{ inputs.system }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      ### N.B this step cannot be placed in a composite action
      ### due to secrets access
      - name: Get system-specific variable names
        id: get_sys_vars
        run: |
          tmp=${{ inputs.system }}
          echo key_var=${tmp^^}_TESTING_KEY >> $GITHUB_OUTPUT
          echo hkey_var=${tmp^^}_HOST_KEY >> $GITHUB_OUTPUT
          echo user_var=${tmp^^}_USER >> $GITHUB_OUTPUT
          echo repo_path_var=${tmp^^}_REPO_PATH >> $GITHUB_OUTPUT
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup ssh
        uses: ./.github/actions/setup_ssh
        with:
          system: ${{ inputs.system }}
          sshkey: ${{ secrets[steps.get_sys_vars.outputs.key_var] }}
          hostkey: ${{ secrets[steps.get_sys_vars.outputs.hkey_var] }}
          user: ${{ secrets[steps.get_sys_vars.outputs.user_var] }}
      - name: Transfer ${{ github.event.repository.name }} repo
        uses: ./.github/actions/prepare_and_transfer_repo
        with:
          system: ${{ inputs.system }}
          repopath: ${{ secrets[steps.get_sys_vars.outputs.repo_path_var] }}
      - name: Set build variables
        uses: ./.github/actions/set_build_vars
        with:
          do_64bit: ${{ inputs.do_64bit }}
          firedrake_repo: ${{ inputs.firedrake_repo }}
          build_branch: ${{ inputs.build_branch }}
      - name: Setup Firedrake source
        uses: ./.github/actions/setup_app_source
        with:
          system: ${{ inputs.system }}
          app: firedrake
          repo: ${{ env.FIREDRAKE_REPO }}
          branch: ${{ inputs.build_branch }}
      - name: Set build command
        env:
          REPO_PATH: ${{ secrets[steps.get_sys_vars.outputs.repo_path_var] }}
        run: | 
          ./.github/scripts/build_submit_command.sh ${{ inputs.system }} firedrake >> $GITHUB_ENV
      - name: Build firedrake
        run: |
          ssh ${{inputs.system}} "cd ${{ secrets[steps.get_sys_vars.outputs.repo_path_var] }}/scripts; ${FIREDRAKE_SUBMIT_COMMAND}"
