name: Build full Firedrake stack on all systems

on:
  workflow_dispatch:

jobs:
  prepare:
    strategy:
      matrix:
        system: [gadi, setonix]
    concurrency:
      group: ${{ matrix.system }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup ssh
        uses: ./.github/actions/setup_ssh
        env:
          TEST_KEY: ${{ secrets[format('{0}_TESTING_KEY',inputs.system)] }}
          HOST_KEY: ${{ secrets[format('{0}_HOST_KEY',inputs.system)] }}
          USER: ${{ secrets[format('{0}_USER',inputs.system)] }}
        with:
          system: ${{ matrix.system }}
      - name: Transfer ${{ github.event.repository.name }} repo
        uses: ./.github/actions/prepare_and_transfer_repo
        env:
          REPO_PATH: ${{ secrets[format('{0}_REPO_PATH',inputs.system)] }}
        with:
          system: ${{ matrix.system }}
      - name: Setup Firedrake source
        uses: ./.github/actions/setup_app_source
        with:
          system: ${{ matrix.system }}
          app: firedrake
          repo: firedrakeproject/firedrake
          branch: ''
          depth: 0
          fetch_latest_tag: true
      - name: Get petsc tag
        id: get_petsc_tag
        run: |
          echo petsc_tag=$( ./firedrake/scripts/firedrake-configure --no-package-manager --petscver ) >> $GITHUB_OUTPUT
      - name: Checkout petsc
        uses: ./.github/actions/setup_app_source_gitlab
        with:
          system: ${{ matrix.system }}
          app: petsc
          repo: petsc/petsc
          branch: ${{ steps.get_petsc_tag.outputs.petsc_tag }}
      - name: Setup G-ADOPT source
        uses: ./.github/actions/setup_app_source
        with:
          system: ${{ matrix.system }}
          app: g-adopt
          repo: g-adopt/g-adopt
          branch: master
          depth: 0
          fetch_latest_tag: true

  build:
    needs: prepare
    continue-on-error: true
    strategy:
      matrix:
        system: [gadi, setonix]
        do_64bit: [false, true]
    concurrency:
      group: ${{ matrix.system }}
    env:
      REPO_PATH: ${{ secrets[format('{0}_REPO_PATH',matrix.system)] }}
    runs-on: ubuntu-latest
    steps:
      ### Run this again because outputs from matrix jobs are
      ### a bit dodgy
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup ssh
        uses: ./.github/actions/setup_ssh
        env:
          TEST_KEY: ${{ secrets[format('{0}_TESTING_KEY',matrix.system)] }}
          HOST_KEY: ${{ secrets[format('{0}_HOST_KEY',matrix.system)] }}
          USER: ${{ secrets[format('{0}_USER',matrix.system)] }}
        with:
          system: ${{ matrix.system }}
      - name: Set build variables
        uses: ./.github/actions/set_build_vars
        with:
          do_64bit: ${{ matrix.do_64bit }}
      - name: Set build commands
        run: | 
          ./.github/scripts/build_submit_command.sh ${{ matrix.system }} petsc >> $GITHUB_ENV
          ./.github/scripts/build_submit_command.sh ${{ matrix.system }} firedrake >> $GITHUB_ENV
          ./.github/scripts/build_submit_command.sh ${{ matrix.system }} gadopt >> $GITHUB_ENV
      - name: Build PETSc
        run: |
          ssh ${{matrix.system}} "cd $REPO_PATH/scripts; ${PETSC_SUBMIT_COMMAND}"
      - name: Build firedrake
        run: |
          ssh ${{matrix.system}} "cd $REPO_PATH/scripts; ${FIREDRAKE_SUBMIT_COMMAND}"
      - name: Build G-ADOPT
        run: |
          ssh ${{matrix.system}} "cd $REPO_PATH/scripts; ${GADOPT_SUBMIT_COMMAND}"