name: Build full Firedrake stack on one system

on:
  workflow_dispatch:
    inputs:
        system:
          description: "Select a system to build on"
          required: true
          type: choice
          options:
            - gadi
            - setonix
        do_64bit:
          description: "Build petsc/firedrake with 64-bit indices?"
          required: false
          type: boolean

concurrency:
  group: ${{ inputs.system }}

jobs:
  build:
    env:
      REPO_PATH: ${{ secrets[format('{0}_REPO_PATH',inputs.system)] }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup ssh
        uses: ./.github/actions/setup_ssh
        env:
          TEST_KEY: ${{ secrets[format('{0}_TESTING_KEY',inputs.system)] }}
          HOST_KEY: ${{ secrets[format('{0}_HOST_KEY',inputs.system)] }}
          USER: ${{ secrets[format('{0}_USER',inputs.system)] }}
        with:
          system: ${{ inputs.system }}
      - name: Transfer ${{ github.event.repository.name }} repo
        uses: ./.github/actions/prepare_and_transfer_repo
        with:
          system: ${{ inputs.system }}
      - name: Setup Firedrake source
        uses: ./.github/actions/setup_app_source
        with:
          system: ${{ inputs.system }}
          app: firedrake
          repo: firedrakeproject/firedrake
          branch: ''
          depth: 0
          fetch_latest_tag: true
      - name: Get petsc tag
        id: get_petsc_tag
        run: |
          echo petsc_tag=$( ./firedrake/scripts/firedrake-configure --no-package-manager --petscver ) >> $GITHUB_OUTPUT
      - name: Checkout petsc
        uses: ./.github/actions/setup_app_source_gitlab
        with:
          system: ${{ inputs.system }}
          app: petsc
          repo: petsc/petsc
          branch: ${{ steps.get_petsc_tag.outputs.petsc_tag }}
      - name: Setup G-ADOPT source
        uses: ./.github/actions/setup_app_source
        with:
          system: ${{ inputs.system }}
          app: g-adopt
          repo: g-adopt/g-adopt
          branch: master
          depth: 0
          fetch_latest_tag: true
      - name: Set build variables
        uses: ./.github/actions/set_build_vars
        with:
          do_64bit: ${{ inputs.do_64bit }}
      - name: Set build commands
        run: | 
          ./.github/scripts/build_submit_command.sh ${{ inputs.system }} petsc >> $GITHUB_ENV
          ./.github/scripts/build_submit_command.sh ${{ inputs.system }} firedrake >> $GITHUB_ENV
          ./.github/scripts/build_submit_command.sh ${{ inputs.system }} gadopt >> $GITHUB_ENV
      - name: Build PETSc
        run: |
          ssh ${{inputs.system}} "cd $REPO_PATH/scripts; ${PETSC_SUBMIT_COMMAND}"
      - name: Build firedrake
        run: |
          ssh ${{inputs.system}} "cd $REPO_PATH/scripts; ${FIREDRAKE_SUBMIT_COMMAND}"
      - name: Build G-ADOPT
        run: |
          ssh ${{inputs.system}} "cd $REPO_PATH/scripts; ${GADOPT_SUBMIT_COMMAND}"