name: Build full Firedrake stack on one system

on:
  workflow_dispatch:
    inputs:
        system:
          description: "Select a system to build on"
          required: true
          type: choice
          options:
            - gadi
            - setonix
        do_64bit:
          description: "Build petsc/firedrake with 64-bit indices?"
          required: false
          type: boolean

concurrency:
  group: ${{ inputs.system }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      ### N.B this step cannot be placed in a composite action
      ### due to secrets access
      - name: Get system-specific variable names
        id: get_sys_vars
        run: |
          tmp=${{ inputs.system }}
          echo key_var=${tmp^^}_TESTING_KEY >> $GITHUB_OUTPUT
          echo hkey_var=${tmp^^}_HOST_KEY >> $GITHUB_OUTPUT
          echo user_var=${tmp^^}_USER >> $GITHUB_OUTPUT
          echo repo_path_var=${tmp^^}_REPO_PATH >> $GITHUB_OUTPUT
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup ssh
        uses: ./.github/actions/setup_ssh
        with:
          system: ${{ inputs.system }}
          sshkey: ${{ secrets[steps.get_sys_vars.outputs.key_var] }}
          hostkey: ${{ secrets[steps.get_sys_vars.outputs.hkey_var] }}
          user: ${{ secrets[steps.get_sys_vars.outputs.user_var] }}
      - name: Transfer ${{ github.event.repository.name }} repo
        uses: ./.github/actions/prepare_and_transfer_repo
        with:
          system: ${{ inputs.system }}
          repopath: ${{ secrets[steps.get_sys_vars.outputs.repo_path_var] }}
      - name: Setup Firedrake source
        uses: ./.github/actions/setup_app_source
        with:
          system: ${{ inputs.system }}
          app: firedrake
          repo: firedrakeproject/firedrake
          branch: ''
          depth: 0
          fetch_latest_tag: true
      - name: Get petsc tag
        id: get_petsc_tag
        run: |
          echo petsc_tag=$( ./firedrake/scripts/firedrake-configure --no-package-manager --petscver ) >> $GITHUB_OUTPUT
      - name: Checkout petsc
        uses: ./.github/actions/setup_app_source_gitlab
        with:
          system: ${{ inputs.system }}
          app: petsc
          repo: petsc/petsc
          branch: ${{ steps.get_petsc_tag.outputs.petsc_tag }}
      - name: Setup G-ADOPT source
        uses: ./.github/actions/setup_app_source
        with:
          system: ${{ inputs.system }}
          app: g-adopt
          repo: g-adopt/g-adopt
          branch: master
          depth: 0
          fetch_latest_tag: true
      - name: Set build variables
        uses: ./.github/actions/set_build_vars
        with:
          do_64bit: ${{ inputs.do_64bit }}
      - name: Set build commands
        env:
          REPO_PATH: ${{ secrets[steps.get_sys_vars.outputs.repo_path_var] }}
        run: | 
          ./.github/scripts/build_submit_command.sh ${{ inputs.system }} petsc >> $GITHUB_ENV
          ./.github/scripts/build_submit_command.sh ${{ inputs.system }} firedrake >> $GITHUB_ENV
          ./.github/scripts/build_submit_command.sh ${{ inputs.system }} gadopt >> $GITHUB_ENV
      - name: Build PETSc
        run: |
          ssh ${{inputs.system}} "cd ${{ secrets[steps.get_sys_vars.outputs.repo_path_var] }}/scripts; ${PETSC_SUBMIT_COMMAND}"
      - name: Build firedrake
        run: |
          ssh ${{inputs.system}} "cd ${{ secrets[steps.get_sys_vars.outputs.repo_path_var] }}/scripts; ${FIREDRAKE_SUBMIT_COMMAND}"
      - name: Build G-ADOPT
        run: |
          ssh ${{inputs.system}} "cd ${{ secrets[steps.get_sys_vars.outputs.repo_path_var] }}/scripts; ${GADOPT_SUBMIT_COMMAND}"