name: Periodic Firedrake Build

on:
  workflow_dispatch:

jobs:
  prepare:
    strategy:
      matrix:
        system: [gadi]
    runs-on: ubuntu-latest
    steps:
      ### N.B this step cannot be placed in a composite action
      ### due to secrets access
      - name: Get system-specific variable names
        id: get_sys_vars
        run: |
          tmp=${{ matrix.system }}
          echo key_var=${tmp^^}_TESTING_KEY >> $GITHUB_OUTPUT
          echo hkey_var=${tmp^^}_HOST_KEY >> $GITHUB_OUTPUT
          echo user_var=${tmp^^}_USER >> $GITHUB_OUTPUT
          echo repo_path_var=${tmp^^}_REPO_PATH >> $GITHUB_OUTPUT
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup ssh
        uses: ./.github/actions/setup_ssh
        with:
          system: ${{ matrix.system }}
          sshkey: ${{ secrets[steps.get_sys_vars.outputs.key_var] }}
          hostkey: ${{ secrets[steps.get_sys_vars.outputs.hkey_var] }}
          user: ${{ secrets[steps.get_sys_vars.outputs.user_var] }}
      - name: Setup PETSc source
        uses: ./.github/actions/setup_app_source
        with:
          system: ${{ matrix.system }}
          app: petsc
          repo: firedrakeproject/petsc
          branch: firedrake
      - name: Setup Firedrake source
        uses: ./.github/actions/setup_app_source
        with:
          system: ${{ matrix.system }}
          app: firedrake
          repo: firedrakeproject/firedrake
          branch: master
      - name: Setup G-ADOPT source
        uses: ./.github/actions/setup_app_source
        with:
          system: ${{ matrix.system }}
          app: g-adopt
          repo: g-adopt/g-adopt
          branch: master

  build:
    needs: prepare
    strategy:
      matrix:
        system: [gadi]
        do_64bit: [false, true]
    runs-on: ubuntu-latest
    steps:
      ### Run this again because outputs from matrix jobs are
      ### a bit dodgy
      - name: Get system-specific variable names
        id: get_sys_vars
        run: |
          tmp=${{ matrix.system }}
          echo key_var=${tmp^^}_TESTING_KEY >> $GITHUB_OUTPUT
          echo hkey_var=${tmp^^}_HOST_KEY >> $GITHUB_OUTPUT
          echo user_var=${tmp^^}_USER >> $GITHUB_OUTPUT
          echo repo_path_var=${tmp^^}_REPO_PATH >> $GITHUB_OUTPUT
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup ssh
        uses: ./.github/actions/setup_ssh
        with:
          system: ${{ matrix.system }}
          sshkey: ${{ secrets[steps.get_sys_vars.outputs.key_var] }}
          hostkey: ${{ secrets[steps.get_sys_vars.outputs.hkey_var] }}
          user: ${{ secrets[steps.get_sys_vars.outputs.user_var] }}
      - name: Set build variables
        uses: ./.github/actions/set_build_vars
        with:
          do_64bit: ${{ matrix.do_64bit }}
      - name: Set build commands
        env:
          REPO_PATH: ${{ secrets[steps.get_sys_vars.outputs.repo_path_var] }}
        run: | 
          ./.github/scripts/build_submit_command.sh ${{ matrix.system }} petsc >> $GITHUB_ENV
          ./.github/scripts/build_submit_command.sh ${{ matrix.system }} firedrake >> $GITHUB_ENV
          ./.github/scripts/build_submit_command.sh ${{ matrix.system }} gadopt >> $GITHUB_ENV
      - name: Build PETSc
        run: |
          ssh ${{matrix.system}} "cd ${{ secrets[steps.get_sys_vars.outputs.repo_path_var] }}/scripts; ${PETSC_SUBMIT_COMMAND}"
      - name: Build firedrake
        run: |
          ssh ${{matrix.system}} "cd ${{ secrets[steps.get_sys_vars.outputs.repo_path_var] }}/scripts; ${FIREDRAKE_SUBMIT_COMMAND}"
      - name: Build G-ADOPT
        run: |
          ssh ${{matrix.system}} "cd ${{ secrets[steps.get_sys_vars.outputs.repo_path_var] }}/scripts; ${GADOPT_SUBMIT_COMMAND}"